name: Unit Test

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
    Unit_Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          pip install pipenv
          pipenv install --dev --skip-lock
      - name: Running coverage test report
        run: |
          pipenv run pytest --cov=./src